package com.example.backend.model.notification;

public enum NotificationType {
    BOOKING_SUBMITTED,
    BOOKING_NEW_PENDING,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_USER_CANCELLED_ALERT,
    TICKET_CREATED_USER,
    TICKET_NEW_FOR_STAFF,
    TICKET_STATUS_CHANGED,
    TICKET_ASSIGNED,
    TICKET_COMMENT,
    TICKET_REJECTED,
    FACILITY_RESOURCE_CREATED,
    FACILITY_RESOURCE_UPDATED,
    FACILITY_RESOURCE_DELETED,
    GENERAL
}
