spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth setup
spring.security.oauth2.client.registration.google.client-id=YOUR_ACTUAL_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_ACTUAL_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile

# Tokens
jwt.expiration=86400000
app.frontend.url=http://localhost:5174
